use anyhow::{Context,Result,ensure};
use image::{DynamicImage,GenericImageView,ImageFormat,imageops::FilterType};
use sha2::{Digest,Sha256};
use std::{fs,io::Cursor,path::Path};
use crate::database::Database;

pub struct Assets;
impl Assets {
	fn source(value:&str)->Result<(Vec<u8>,String)>{if let Ok(url)=url::Url::parse(value){ensure!(matches!(url.scheme(),"http"|"https"),"Use an HTTP/HTTPS image URL or local path");let response=reqwest::blocking::Client::builder().timeout(std::time::Duration::from_secs(10)).redirect(reqwest::redirect::Policy::limited(3)).build()?.get(url.clone()).send()?;ensure!(response.status().is_success(),"Remote image could not be downloaded");ensure!(response.content_length().is_none_or(|size|size<=5*1048576),"Image exceeds 5 MiB");let bytes=response.bytes()?.to_vec();ensure!(bytes.len()<=5*1048576,"Image exceeds 5 MiB");Ok((bytes,url.to_string()))}else{let path=Path::new(value);let metadata=fs::metadata(path).with_context(||format!("Cannot read image {}",path.display()))?;ensure!(metadata.is_file()&&metadata.len()<=5*1048576,"Choose an image up to 5 MiB");Ok((fs::read(path)?,String::new()))}}
	pub fn normalize(bytes:&[u8],source_url:&str)->Result<(serde_json::Value,Vec<u8>)>{ensure!(!bytes.is_empty()&&bytes.len()<=5*1048576,"Choose an image up to 5 MiB");let format=image::guess_format(bytes)?;ensure!(matches!(format,ImageFormat::Png|ImageFormat::Jpeg|ImageFormat::WebP|ImageFormat::Gif),"Use PNG, JPG, WebP, or GIF");let decoded=image::load_from_memory_with_format(bytes,format)?;let(width,height)=decoded.dimensions();ensure!(width>0&&height>0&&width<=16384&&height<=16384,"Invalid image dimensions");let animated=format==ImageFormat::Gif;let(data,mime)=if animated{(bytes.to_vec(),"image/gif")}else{let image=if width>2048||height>2048{decoded.resize(2048,2048,FilterType::Lanczos3)}else{decoded};let mut output=Cursor::new(Vec::new());if image.color().has_alpha(){image.write_to(&mut output,ImageFormat::Png)?;(output.into_inner(),"image/png")}else{let mut encoder=image::codecs::jpeg::JpegEncoder::new_with_quality(&mut output,86);encoder.encode_image(&DynamicImage::ImageRgb8(image.to_rgb8()))?;(output.into_inner(),"image/jpeg")}};ensure!(data.len()<=2*1048576,"Normalized image exceeds 2 MiB");let(width,height)=image::load_from_memory(&data)?.dimensions();let id=format!("{:x}",Sha256::digest(&data));let metadata=serde_json::json!({"id":id,"mime_type":mime,"size":data.len(),"width":width,"height":height,"animated":animated,"source_urls":if source_url.is_empty(){serde_json::json!([])}else{serde_json::json!([source_url])}});Ok((metadata,data))}
	pub fn import(db:&Database,value:&str)->Result<serde_json::Value>{let(bytes,source)=Self::source(value.trim())?;let(metadata,data)=Self::normalize(&bytes,&source)?;db.put_asset(&metadata,&data,false)?;Ok(metadata)}
	pub fn accept(db:&Database,bytes:&[u8],id:&str,uploaded:bool)->Result<serde_json::Value>{ensure!(bytes.len()<=2*1048576&&format!("{:x}",Sha256::digest(bytes))==id,"Bundle asset hash mismatch");let format=image::guess_format(bytes)?;ensure!(matches!(format,ImageFormat::Png|ImageFormat::Jpeg|ImageFormat::WebP|ImageFormat::Gif),"Invalid bundle image");let image=image::load_from_memory_with_format(bytes,format)?;let(width,height)=image.dimensions();ensure!(width<=2048&&height<=2048,"Bundle image dimensions exceed limits");let mime=match format{ImageFormat::Png=>"image/png",ImageFormat::Jpeg=>"image/jpeg",ImageFormat::WebP=>"image/webp",_=>"image/gif"};let metadata=serde_json::json!({"id":id,"mime_type":mime,"size":bytes.len(),"width":width,"height":height,"animated":format==ImageFormat::Gif,"source_urls":[]});db.put_asset(&metadata,bytes,uploaded)?;Ok(metadata)}
}
