use crate::config::{Document, Match};
use anyhow::{Result, ensure};
use serde::{Deserialize, Serialize};
use typerelay_core::{Snapshot, Snippet};

#[derive(Deserialize)]
pub struct Request { pub yaml: Option<String>, pub matches: Option<Vec<Match>>, #[serde(default)] pub export: bool, #[serde(default)] pub edits: Vec<Edit> }
#[derive(Deserialize)]
pub struct Edit { pub index: Option<usize>, pub entry: Option<Match> }
#[derive(Serialize)]
pub struct Response { #[serde(skip_serializing_if = "Option::is_none")] pub yaml: Option<String>, pub matches: Vec<Match> }
pub struct Bridge;
impl Bridge {
    pub const HEADER: &str = "# Generated by TypeRelay.\n# Edit snippets through the TypeRelay TUI or web app.\n# Changes made in a text editor are not synchronized.\n";
    pub fn validate(entries: &[Match]) -> Result<Snapshot> {
        let mut snippets = Vec::new();
        for entry in entries {
            ensure!(matches!(entry.kind.as_str(), "plain_text" | "code" | "template" | "rich_text"), "Unsupported snippet type");
            ensure!(entry.title.len() <= 500 && !entry.title.chars().any(char::is_control), "Title must be at most 500 bytes without control characters");
            ensure!(!entry.language.is_empty() && entry.language.len() <= 100 && !entry.language.chars().any(char::is_control), "Invalid language");
            if entry.kind == "template" { typerelay_core::template::Template { text: entry.replace.clone(), variables: entry.variables.clone() }.normalize().map_err(anyhow::Error::msg)?; }
            let replacement=if entry.kind=="rich_text" {typerelay_core::rich_text::RichText::render(typerelay_core::rich_text::RichRequest{markdown:entry.replace.clone(),variables:entry.variables.clone(),preview:true,..Default::default()}).map_err(anyhow::Error::msg)?.text}else{entry.replace.clone()};
            let snippet = Snippet { trigger: if entry.trigger.is_empty() { "validation".into() } else { entry.trigger.clone() }, replacement };
            Snapshot::new(vec![snippet.clone()]).map_err(anyhow::Error::msg)?;
            if !entry.trigger.is_empty() { snippets.push(snippet); }
        }
        let mut snapshot = Snapshot::new(snippets).map_err(anyhow::Error::msg)?;
        for entry in entries.iter().filter(|entry| entry.kind == "template" && !entry.trigger.is_empty()) { snapshot.set_template(&entry.trigger, typerelay_core::template::Template { text: entry.replace.clone(), variables: entry.variables.clone() }).map_err(anyhow::Error::msg)?; }
        for entry in entries.iter().filter(|entry|entry.kind=="rich_text"&&!entry.trigger.is_empty()){let rendered=typerelay_core::rich_text::RichText::render(typerelay_core::rich_text::RichRequest{markdown:entry.replace.clone(),variables:entry.variables.clone(),preview:true,..Default::default()}).map_err(anyhow::Error::msg)?;snapshot.set_rich(&entry.trigger,!rendered.fields.is_empty());}
        Ok(snapshot)
    }
    pub fn export(entries: &[Match]) -> Result<String> {
        Self::validate(entries)?;
        Ok(format!("{}{}", Self::HEADER, serde_saphyr::to_string(&Document { matches: entries.to_vec() })?))
    }
    pub fn execute(request: Request) -> Result<Response> {
        let export = request.export || request.yaml.is_some();
        let mut matches = if let Some(yaml) = request.yaml {
            ensure!(yaml.len() <= 1_048_576, "Snippet file exceeds 1 MiB");
            serde_saphyr::from_str::<Document>(&yaml)?.matches
        } else { request.matches.unwrap_or_default() };
        Self::validate(&matches)?;
        for edit in request.edits {
            if let Some(index) = edit.index {
                ensure!(index < matches.len(), "Snippet no longer exists");
                if let Some(entry) = edit.entry { matches[index] = entry; } else { matches.remove(index); }
            } else if let Some(entry) = edit.entry { matches.push(entry); }
        }
        Self::validate(&matches)?;
        let yaml = if export { Some(Self::export(&matches)?) } else { None };
        Ok(Response { yaml, matches })
    }
}
