use crate::config::{Document, Match};
use anyhow::{Result, ensure};
use serde::{Deserialize, Serialize};
use typerelay_core::{Snapshot, Snippet};

#[derive(Deserialize)]
pub struct Request { pub yaml: Option<String>, pub matches: Option<Vec<Match>>, #[serde(default)] pub export: bool, #[serde(default)] pub edits: Vec<Edit> }
#[derive(Deserialize)]
pub struct Edit { pub index: Option<usize>, pub entry: Option<Match> }
#[derive(Serialize)]
pub struct Response { #[serde(skip_serializing_if = "Option::is_none")] pub yaml: Option<String>, pub matches: Vec<Match> }
pub struct Bridge;
impl Bridge {
    pub const HEADER: &str = "# Generated by TypeRelay.\n# Edit snippets through the TypeRelay TUI or web app.\n# Changes made in a text editor are not synchronized.\n";
    pub fn validate(entries: &[Match]) -> Result<Snapshot> {
        Snapshot::new(entries.iter().map(|entry| Snippet { trigger: entry.trigger.clone(), replacement: entry.replace.clone() }).collect()).map_err(anyhow::Error::msg)
    }
    pub fn export(entries: &[Match]) -> Result<String> {
        Self::validate(entries)?;
        Ok(format!("{}{}", Self::HEADER, serde_saphyr::to_string(&Document { matches: entries.to_vec() })?))
    }
    pub fn execute(request: Request) -> Result<Response> {
        let export = request.export || request.yaml.is_some();
        let mut matches = if let Some(yaml) = request.yaml {
            ensure!(yaml.len() <= 1_048_576, "Snippet file exceeds 1 MiB");
            serde_saphyr::from_str::<Document>(&yaml)?.matches
        } else { request.matches.unwrap_or_default() };
        Self::validate(&matches)?;
        for edit in request.edits {
            if let Some(index) = edit.index {
                ensure!(index < matches.len(), "Snippet no longer exists");
                if let Some(entry) = edit.entry { matches[index] = entry; } else { matches.remove(index); }
            } else if let Some(entry) = edit.entry { matches.push(entry); }
        }
        Self::validate(&matches)?;
        let yaml = if export { Some(Self::export(&matches)?) } else { None };
        Ok(Response { yaml, matches })
    }
}
