import { before, after, test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { execFile, spawn } from 'node:child_process';
import { JSDOM } from 'jsdom';
import { randomUUID } from 'node:crypto';
import { mongoose, Account, Member, User, Device, Ticket, Library } from '../model/index.js';
import { Support } from '../services/support.js';
import { Auth } from '../services/auth.js';
import { Libraries } from '../services/libraries.js';

class Fixture {
	static root; static server; static actor; static account; static cookie; static csrf; static one; static two;
	static origin = 'http://127.0.0.1:3140';
	static async request(path, method = 'GET', body) {
		const response = await fetch(Fixture.origin + path, { method, redirect: 'manual', headers: { Cookie: Fixture.cookie || '', 'Content-Type': 'application/json', 'X-CSRF-Token': Fixture.csrf || '', 'X-Account-Id': Fixture.account || '' }, body: body ? JSON.stringify({ operation_id: randomUUID(), ...body }) : undefined });
		if (response.headers.get('set-cookie')) Fixture.cookie = response.headers.get('set-cookie').split(';')[0];
		return response;
	}
	static async json(path, method, body) { const response = await Fixture.request('/api/v2/' + path, method, body); const result = await response.json(); assert.equal(response.status, 200, JSON.stringify(result)); return result; }
	static async device(name, user = Fixture.actor.user, account = Fixture.account) {
		const root = join(Fixture.root, name);
		await mkdir(join(root, 'typerelay/snippets'), { recursive: true });
		await mkdir(join(root, 'typerelay/sync'), { recursive: true });
		const access = Support.token(); const refresh = Support.token();
		const device = await Device.create({ account, user, name, access: Support.hash(access), access_expires: new Date(Date.now() + 900000), refresh: Support.hash(refresh), refresh_expires: new Date(Date.now() + 86400000) });
		await writeFile(join(root, 'typerelay/sync/credentials.json'), JSON.stringify({ server: Fixture.origin, access_token: access, refresh_token: refresh }), { mode: 0o600 });
		return { root, device, config: join(root, 'typerelay'), snippets: join(root, 'typerelay/snippets') };
	}
	static async cli(device, ...args) { return promisify(execFile)('/usr/local/bin/typerelay', args, { env: { ...process.env, XDG_CONFIG_HOME: device.root }, timeout: 30000 }); }
	static async state(device) { return JSON.parse((await Fixture.cli(device, 'inspect')).stdout); }
	static async edit(device, name, trigger, text) { return Fixture.cli(device, 'database-edit', name, trigger, ...(text === null ? ['--trash'] : ['--text', text])); }
}
before(async () => {
	process.env.NODE_ENV = 'test';
	process.env.PORT = '3140';
	process.env.MONGODB_URI = process.env.MONGODB_URI.replace('/typerelay?', '/typerelay_e2e?');
	Fixture.root = await mkdtemp(join(tmpdir(), 'typerelay-e2e-'));
	process.env.SESSION_SECRET_FILE = join(Fixture.root, 'session');
	const { Server } = await import('../app.js');
	Fixture.server = await Server.start();
	const user = await User.create({ email: randomUUID() + '@example.test', name: 'Test owner' });
	const account = await Account.create({ name: 'Test team' });
	await Member.create({ user: user._id, account: account._id, role: 'owner' });
	Fixture.account = String(account._id);
	Fixture.actor = await Support.context(String(user._id), Fixture.account);
	const token = Support.token();
	await Ticket.create({ hash: Support.hash(token), kind: 'login', email: user.email, expires: new Date(Date.now() + 60000) });
	await Fixture.request('/auth/callback?token=' + token);
	const html = await (await Fixture.request('/')).text();
	const dom = new JSDOM(html);
	Fixture.csrf = dom.window.document.querySelector('meta[name=csrf-token]').content;
	dom.window.close();
	Fixture.one = await Fixture.device('one');
	Fixture.two = await Fixture.device('two');
});
after(async () => {
	await new Promise(resolve => Fixture.server.close(resolve));
	await mongoose.connection.dropDatabase();
	await mongoose.disconnect();
	await rm(Fixture.root, { recursive: true, force: true });
});
test('actual desktop browser PKCE flow writes private credentials and settings', async () => {
	const root = join(Fixture.root, 'browser-connect');
	const child = spawn('/usr/local/bin/typerelay', ['connect', '--server', Fixture.origin, '--no-browser'], { env: { ...process.env, XDG_CONFIG_HOME: root } });
	const completed = new Promise((resolve, reject) => { child.on('exit', code => code === 0 ? resolve() : reject(new Error('CLI failed ' + code))); child.on('error', reject); });
	try {
		const authorize = await new Promise((resolve, reject) => {
			let output = '';
			const timer = setTimeout(() => reject(new Error('CLI did not print authorization URL')), 5000);
			child.stdout.on('data', data => { output += data; const match = output.match(/http[^\s]+oauth\/authorize[^\s]+/); if (match) { clearTimeout(timer); resolve(new URL(match[0])); } });
			child.on('exit', code => { if (code) { clearTimeout(timer); reject(new Error('CLI exited ' + code)); } });
		});
		const page = await Fixture.request(authorize.pathname + authorize.search);
		assert.ok(page.headers.get('content-security-policy').includes("form-action 'self' " + new URL(authorize.searchParams.get('redirect_uri')).origin + ';'));
		const dom = new JSDOM(await page.text(), { url: authorize.href, runScripts: 'outside-only' });
		dom.window.eval((await readFile('./public/app.js', 'utf8')).replace("import { Abbreviation } from './abbreviation.js';", (await readFile('./public/abbreviation.js', 'utf8')).replace('export class', 'class')).replace('export { client };', ''));
		const form = dom.window.document.querySelector('form[action="/oauth/authorize"]');
		form.elements.account.value = Fixture.account;
		const submit = new dom.window.Event('submit', { bubbles: true, cancelable: true });
		assert.equal(form.dispatchEvent(submit), true, 'Shared JavaScript must not cancel the native OAuth form');
		assert.equal(submit.defaultPrevented, false);
		const fields = Object.fromEntries(new dom.window.FormData(form));
		dom.window.close();
		const approval = await Fixture.request('/oauth/authorize', 'POST', fields);
		assert.equal(approval.status, 302);
		const callback = await fetch(approval.headers.get('location'));
		assert.equal(callback.status, 200);
		await completed;
		const credentialsPath = join(root, 'typerelay/sync/credentials.json');
		const credentials = JSON.parse(await readFile(credentialsPath, 'utf8'));
		assert.equal((await Auth.bearer(credentials.access_token)).account, Fixture.account);
		assert.ok((await readFile(join(root, 'typerelay/settings.yml'), 'utf8')).includes(Fixture.origin));
	} finally { child.kill(); await completed.catch(() => {}); }
});
test('SQLite two-device edits, conflict recovery and generated YAML isolation', async () => {
	const yaml = '# original comments\nmatches:\n- trigger: alpha\n  replace: First\n- trigger: beta\n  replace: Second\n';
	await writeFile(join(Fixture.one.snippets, 'mine.yml'), yaml);
	await writeFile(join(Fixture.one.snippets, 'local-only.yml'), 'matches: [{trigger: local, replace: Only here}]\n');
	await Fixture.cli(Fixture.one, 'enroll', 'mine.yml');
	await Fixture.cli(Fixture.one, 'sync');
	await Fixture.cli(Fixture.two, 'sync');
	let one = await Fixture.state(Fixture.one);
	let two = await Fixture.state(Fixture.two);
	const library = one.libraries.find(row => row.name === 'mine.yml');
	assert.equal(two.libraries.filter(row => row.state === 'active').length, 1);
	assert.ok(!two.libraries.some(row => row.name === 'local-only.yml'));
	await Fixture.edit(Fixture.one, 'mine.yml', 'alpha', 'Device one');
	await Fixture.edit(Fixture.two, 'mine.yml', 'beta', 'Device two');
	await Fixture.cli(Fixture.one, 'sync');
	await Fixture.cli(Fixture.two, 'sync');
	await Fixture.cli(Fixture.one, 'sync');
	two = await Fixture.state(Fixture.two);
	assert.deepEqual(two.libraries.find(row => row._id === library._id).records.filter(row => row.state === 'active').map(row => row.content.text), ['Device one', 'Device two']);
	await Fixture.edit(Fixture.one, 'mine.yml', 'alpha', 'Winner');
	await Fixture.edit(Fixture.two, 'mine.yml', 'alpha', 'Conflicting draft');
	await Fixture.cli(Fixture.one, 'sync');
	await Fixture.cli(Fixture.two, 'sync');
	two = await Fixture.state(Fixture.two);
	assert.equal(two.conflicts.length, 1);
	assert.ok(two.recovery > 0);
	assert.equal(two.libraries.find(row => row._id === library._id).records.find(row => row.trigger === 'alpha').content.text, 'Winner');
	const exportPath = join(Fixture.two.snippets, 'export.yml');
	await Fixture.cli(Fixture.two, 'export', 'mine.yml', exportPath);
	assert.ok((await readFile(exportPath, 'utf8')).startsWith('# Generated by TypeRelay.'));
	await writeFile(exportPath, 'matches: [{trigger: alpha, replace: Tampered}]');
	await Fixture.cli(Fixture.two, 'sync');
	assert.equal((await Fixture.state(Fixture.two)).libraries.find(row => row._id === library._id).records.find(row => row.trigger === 'alpha').content.text, 'Winner');
	// Remote collision is staged and does not replace the last working local snapshot.
	const source = join(Fixture.two.root, 'collision.yml');
	await writeFile(source, 'matches: [{trigger: collision, replace: Local}]');
	await Fixture.cli(Fixture.two, 'import', source, '--name', 'Local collision');
	await Fixture.json('libraries', 'POST', { name: 'Remote collision', snippets: [{ trigger: 'collision', content: { version: 1, type: 'plain_text', text: 'Remote' } }] });
	await assert.rejects(Fixture.cli(Fixture.two, 'sync'), /[Dd]uplicate/);
	two = await Fixture.state(Fixture.two);
	assert.ok(two.staged);
	assert.ok(!two.libraries.some(row => row.name === 'Remote collision'));
	await Fixture.edit(Fixture.two, 'Local collision', 'collision', null);
	await Fixture.cli(Fixture.two, 'sync');
	assert.ok((await Fixture.state(Fixture.two)).libraries.some(row => row.name === 'Remote collision'));
});
test('offline SQLite outbox and lost-response replay create a library only once', async () => {
	const device = await Fixture.device('offline');
	const credentialsPath = join(device.config, 'sync/credentials.json');
	const credentials = JSON.parse(await readFile(credentialsPath, 'utf8'));
	await writeFile(join(device.snippets, 'offline.yml'), 'matches: [{trigger: offline, replace: Queued}]\n');
	await writeFile(credentialsPath, JSON.stringify({ ...credentials, server: 'http://127.0.0.1:1' }));
	await Fixture.cli(device, 'enroll', 'offline.yml');
	await assert.rejects(Fixture.cli(device, 'sync'));
	const pending = (await Fixture.state(device)).pending[0][1];
	assert.ok(pending.body.operation_id);
	await writeFile(credentialsPath, JSON.stringify(credentials));
	await Fixture.cli(device, 'sync');
	await Fixture.cli(device, 'database-replay', JSON.stringify(pending));
	await Fixture.cli(device, 'sync');
	assert.equal(await Library.countDocuments({ account: Fixture.account, name: 'offline.yml' }), 1);
});
test('permission changes reject local writes, preserve pending drafts and remove revoked records', async () => {
	const user = await User.create({ email: randomUUID() + '@example.test', name: 'Member' });
	await Member.create({ account: Fixture.account, user: user._id, role: 'member' });
	const device = await Fixture.device('member', String(user._id));
	let { library } = await Fixture.json('libraries', 'POST', { name: 'Team library', snippets: [{ trigger: 'team', content: { version: 1, type: 'plain_text', text: 'Authorized' } }] });
	({ library } = await Fixture.json('libraries/' + library._id, 'PATCH', { base_revision: library.revision, name: library.name, shared: true, editable: true, members: [String(user._id)], groups: [] }));
	await Fixture.cli(device, 'sync');
	await Fixture.edit(device, 'Team library', 'team', 'Unsent draft');
	({ library } = await Fixture.json('libraries/' + library._id, 'PATCH', { base_revision: library.revision, name: library.name, shared: true, editable: false, members: [String(user._id)], groups: [] }));
	await Fixture.cli(device, 'sync');
	const state = await Fixture.state(device);
	assert.ok(state.recovery > 0);
	assert.equal(state.libraries.find(row => row._id === library._id).records[0].content.text, 'Authorized');
	await assert.rejects(Fixture.edit(device, 'Team library', 'team', 'Blocked'), /read-only/);
	await Fixture.json('libraries/' + library._id, 'PATCH', { base_revision: library.revision, name: library.name, shared: false, editable: false, members: [], groups: [] });
	await Fixture.cli(device, 'sync');
	assert.ok(!(await Fixture.state(device)).libraries.some(row => row.state === 'active'));
});
test('Trash and restore cross devices; Empty Trash purges copies and protocol v1 is rejected', async () => {
	const device = await Fixture.device('trash-device');
	let { library } = await Fixture.json('libraries', 'POST', { name: 'Trash sync', snippets: [{ trigger: 'trashsync', content: { version: 1, type: 'plain_text', text: 'Recover me' } }] });
	await Fixture.cli(device, 'sync');
	await Fixture.edit(device, 'Trash sync', 'trashsync', null);
	await Fixture.cli(device, 'sync');
	let items = (await Fixture.json('trash')).items;
	const target = items.find(item => item.library === library._id);
	assert.ok(target);
	await Fixture.json('trash/action', 'POST', { target, action: 'restore' });
	await Fixture.cli(device, 'sync');
	assert.equal((await Fixture.state(device)).libraries.find(row => row._id === library._id).records[0].state, 'active');
	await Fixture.edit(device, 'Trash sync', 'trashsync', null);
	await Fixture.cli(device, 'sync');
	items = (await Fixture.json('trash')).items;
	await Fixture.json('trash/empty', 'POST', { targets: items.filter(item => item.library === library._id) });
	await Fixture.cli(device, 'sync');
	const record = (await Fixture.state(device)).libraries.find(row => row._id === library._id).records[0];
	assert.equal(record.state, 'purged');
	assert.equal(record.content, undefined);
	const legacy = await Fixture.request('/api/v1/sync');
	assert.equal(legacy.status, 426);
});
test('offline moves with pending enrollment and later edits sync exactly once; rejected moves recover', async () => {
	const one = await Fixture.device('move-one');
	const two = await Fixture.device('move-two');
	const sourceFile = join(one.root, 'source.yml');
	const destinationFile = join(one.root, 'dest.yml');
	await writeFile(sourceFile, 'matches: [{trigger: movingone, replace: One}, {trigger: movingtwo, replace: Two}]');
	await writeFile(destinationFile, 'matches: []');
	await Fixture.cli(one, 'import', sourceFile, '--name', 'Move source');
	await Fixture.cli(one, 'import', destinationFile, '--name', 'Move destination');
	await Fixture.cli(one, 'enroll', 'Move source');
	await Fixture.cli(one, 'enroll', 'Move destination');
	await Fixture.cli(one, 'database-batch', 'Move source', '--destination', 'Move destination', '--triggers', 'movingone');
	await Fixture.edit(one, 'Move destination', 'movingone', 'Edited offline after move');
	const before = await Fixture.state(one);
	const id = before.libraries.find(row => row.name === 'Move destination').records[0].id;
	await Fixture.cli(one, 'sync');
	await Fixture.cli(two, 'sync');
	let state = await Fixture.state(two);
	let destination = state.libraries.find(row => row.name === 'Move destination');
	assert.equal(destination.records.find(row => row.id === id).content.text, 'Edited offline after move');
	assert.equal(state.libraries.flatMap(row => row.records).filter(row => row.id === id && row.state === 'active').length, 1);
	assert.ok(!(await Fixture.state(one)).pending.length);
	// Other device edits while this device queues a move.
	await Fixture.cli(one, 'database-batch', 'Move destination', '--destination', 'Move source', '--triggers', 'movingone');
	await Fixture.edit(two, 'Move destination', 'movingone', 'Other device wins');
	await Fixture.cli(two, 'sync');
	await Fixture.cli(one, 'sync');
	state = await Fixture.state(one);
	assert.ok(state.recovery > 0);
	assert.equal(state.libraries.find(row => row.name === 'Move destination').records.find(row => row.id === id).content.text, 'Other device wins');
	assert.ok(!state.pending.length);
	// Stale edit to the former location cannot recreate the moved record.
	await Fixture.edit(one, 'Move destination', 'movingone', 'Stale location edit');
	await Fixture.cli(two, 'database-batch', 'Move destination', '--destination', 'Move source', '--triggers', 'movingone');
	await Fixture.cli(two, 'sync');
	await Fixture.cli(one, 'sync');
	state = await Fixture.state(one);
	assert.equal(state.libraries.flatMap(row => row.records).filter(row => row.id === id && row.state === 'active').length, 1);
	assert.equal(state.libraries.find(row => row.name === 'Move source').records.find(row => row.id === id).content.text, 'Other device wins');
	const credentials = JSON.parse(await readFile(join(one.config, 'sync/credentials.json'), 'utf8'));
	const old = await fetch(Fixture.origin + '/api/v2/sync', { headers: { Authorization: 'Bearer ' + credentials.access_token } });
	assert.equal(old.status, 426);
});
test('moving into an inaccessible library cannot resurrect a stale source edit', async () => {
	const user = await User.create({ email: randomUUID() + '@example.test', name: 'Move member' });
	await Member.create({ account: Fixture.account, user: user._id, role: 'member' });
	const device = await Fixture.device('move-limited', String(user._id));
	let source = (await Fixture.json('libraries', 'POST', { name: 'Visible source', yaml: 'matches: [{trigger: restrictedmove, replace: Original}]' })).library;
	const destination = (await Fixture.json('libraries', 'POST', { name: 'Private destination', yaml: 'matches: []' })).library;
	source = (await Fixture.json('libraries/' + source._id, 'PATCH', { base_revision: source.revision, name: source.name, shared: true, editable: true, members: [String(user._id)], groups: [] })).library;
	await Fixture.cli(device, 'sync');
	await Fixture.edit(device, 'Visible source', 'restrictedmove', 'Unsent member draft');
	await Fixture.json('snippets/batch', 'POST', { action: 'move', source_library: source._id, destination_library: destination._id, items: [{ id: source.snippets[0].id, base_revision: source.snippets[0].revision }] });
	await Fixture.cli(device, 'sync');
	const state = await Fixture.state(device);
	assert.ok(!state.libraries.some(row => row._id === destination._id));
	assert.ok(!state.libraries.flatMap(row => row.records).some(row => row.id === source.snippets[0].id && row.state === 'active'));
	assert.ok(!state.pending.length);
	assert.ok(state.recovery > 0);
});
test('web AJAX updates only affected snippets; preserves panel, filter and multiline', async () => {
	const { library } = await Fixture.json('libraries', 'POST', { name: 'Browser library', yaml: 'matches: [{trigger: web, replace: Before}, {trigger: untouched, replace: Keep}]\n' });
	const html = await (await Fixture.request('/')).text();
	const dom = new JSDOM(html, { url: Fixture.origin, runScripts: 'outside-only' });
	const errors = [];
	dom.window.Swal = { fire: async value => { if (value.icon === 'error') errors.push(value.title); return { isConfirmed: true }; } };
	dom.window.bootstrap = { Modal: { getOrCreateInstance: () => ({ show() {}, hide() {} }), getInstance: () => ({ hide() {} }) } };
	dom.window.fetch = async (path, options = {}) => {
		const response = await fetch(new URL(path, Fixture.origin), { ...options, headers: { ...options.headers, Cookie: Fixture.cookie } });
		return response;
	};
	const source = (await readFile('./public/app.js', 'utf8')).replace("import { Abbreviation } from './abbreviation.js';", (await readFile('./public/abbreviation.js', 'utf8')).replace('export class', 'class')).replace('new TypeRelay();', 'window.client = new TypeRelay();').replace('export { client };', '');
	dom.window.eval(source);
	const client = dom.window.client;
	await client.open(library._id);
	const editSnippet = client.editSnippet.bind(client);
	const confirm = client.confirm;
	const opened = [];
	client.editSnippet = async (current, id) => { opened.push(id); };
	const row = dom.window.document.querySelector('[data-snippet="' + library.snippets[0].id + '"]');
	await client.onClick({ target: row.querySelector('pre') });
	assert.deepEqual(opened, [library.snippets[0].id]);
	client.confirm = async () => false;
	await client.onClick({ target: row.querySelector('[data-delete-snippet]') });
	assert.equal(opened.length, 1, 'Trash must not also open the editor');
	row.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
	assert.equal(opened.length, 2);
	client.editSnippet = editSnippet;
	client.confirm = confirm;
	assert.ok(dom.window.document.querySelector('aside .library-controls #account-switch'));
	assert.ok(dom.window.document.querySelector('aside .library-controls #new-library'));
	const actions = dom.window.document.querySelector('.editor-actions');
	assert.ok(actions.querySelector('[data-add-snippet]') && actions.querySelector('[data-library-settings]'));
	const topButton = dom.window.document.querySelector('#scroll-top');
	Object.defineProperty(dom.window.document.documentElement, 'scrollHeight', { configurable: true, value: 2000 });
	Object.defineProperty(dom.window, 'innerHeight', { configurable: true, value: 1000 });
	Object.defineProperty(dom.window, 'scrollY', { configurable: true, writable: true, value: 500 });
	client.updateScrollTop();
	assert.ok(!topButton.classList.contains('is-visible'));
	dom.window.scrollY = 501;
	client.updateScrollTop();
	assert.ok(topButton.classList.contains('is-visible'));
	assert.equal(topButton.tabIndex, 0);
	let scrolling;
	dom.window.matchMedia = () => ({ matches: false });
	dom.window.scrollTo = options => { scrolling = options; dom.window.scrollY = 0; };
	await client.onClick({ target: topButton });
	assert.equal(scrolling.top, 0);
	assert.equal(scrolling.behavior, 'smooth');
	client.updateScrollTop();
	assert.equal(topButton.tabIndex, -1);
	Object.defineProperty(dom.window.document.documentElement, 'scrollHeight', { configurable: true, value: 1000 });
	client.updateScrollTop();
	assert.ok(!topButton.classList.contains('is-visible'), 'Short pages must not show scroll-to-top');
	const boxes = [...dom.window.document.querySelectorAll('[data-select-snippet]')];
	boxes[0].click();
	assert.equal(client.selectedSnippets.size, 1);
	assert.equal(dom.window.document.querySelector('[data-select-all]').indeterminate, true);
	boxes[1].dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true, shiftKey: true }));
	assert.equal(client.selectedSnippets.size, 2);
	assert.equal(dom.window.document.querySelector('[data-select-all]').checked, true);
	dom.window.document.querySelector('[data-select-all]').click();
	assert.equal(client.selectedSnippets.size, 0);
	assert.equal(dom.window.document.querySelector('.bulk-actions').hidden, true);
	const panel = dom.window.document.querySelector('#editor');
	const untouched = dom.window.document.querySelector('[data-snippet="' + library.snippets[1].id + '"]');
	const search = dom.window.document.querySelector('#search');
	search.value = 'Browser';
	search.focus();
	await client.snippet(library.snippets[0].id, { trigger: 'web', replace: 'First\nSecond\n\n' });
	assert.equal(dom.window.document.querySelector('#editor'), panel);
	assert.equal(dom.window.document.querySelector('[data-snippet="' + library.snippets[1].id + '"]'), untouched);
	assert.equal(search.value, 'Browser');
	assert.equal(dom.window.document.activeElement, search);
	assert.equal(dom.window.document.querySelector('[data-snippet="' + library.snippets[0].id + '"] pre').textContent, 'First\nSecond\n\n');
	assert.deepEqual(errors, []);
	const hiddenUser = await User.create({ email: randomUUID() + '@example.test', name: 'Private member' });
	await Member.create({ account: Fixture.account, user: hiddenUser._id, role: 'member' });
	const hiddenCtx = await Support.context(String(hiddenUser._id), Fixture.account);
	await Libraries.mutate(hiddenCtx, randomUUID(), {}, async (ctx, session) => ({ library: await Libraries.create(ctx, { name: 'HiddenNavTest', yaml: 'matches: [{trigger: hiddennav, replace: SecretOnly}]' }, session) }));
	const hiddenResults = await client.request('search?q=hiddennav', 'GET', null, true);
	assert.ok(!hiddenResults.includes('SecretOnly') && !hiddenResults.includes('HiddenNavTest'));
	// Settings switch panes without discarding draft DOM or navigating.
	const draft = dom.window.document.querySelector('#profile-name');
	draft.value = 'Unsaved profile draft';
	await client.onClick({ target: dom.window.document.querySelector('[data-settings-tab="security"]') });
	assert.equal(dom.window.document.querySelector('#settings-pane-profile').hidden, true);
	assert.equal(dom.window.document.querySelector('#settings-pane-security').hidden, false);
	client.settingsTab('profile');
	assert.equal(dom.window.document.querySelector('#profile-name'), draft);
	assert.equal(draft.value, 'Unsaved profile draft');
	assert.ok(![...dom.window.document.querySelectorAll('h1')].some(node => node.textContent === 'Your libraries'));
	assert.ok(dom.window.document.querySelector('header #search-trigger'));
	// Every part of the card loads its library, including the count/badge area.
	const card = dom.window.document.querySelector('[data-id="' + library._id + '"]');
	client.selected = null;
	await client.onClick({ target: card.querySelector('.text-muted') });
	assert.equal(client.selected, library._id);
	assert.equal(card.getAttribute('role'), 'button');
	const modal = dom.window.document.querySelector('#search-modal');
	dom.window.bootstrap.Modal.getOrCreateInstance = element => ({ show() { element.classList.add('show'); }, hide() { element.classList.remove('show'); element.dispatchEvent(new dom.window.Event('hidden.bs.modal')); } });
	dom.window.bootstrap.Modal.getInstance = dom.window.bootstrap.Modal.getOrCreateInstance;
	for (const options of [{ key: '/' }, { key: 'k', ctrlKey: true }, { key: 'k', metaKey: true }]) {
		modal.classList.remove('show');
		const event = new dom.window.KeyboardEvent('keydown', { ...options, bubbles: true, cancelable: true });
		dom.window.document.body.dispatchEvent(event);
		assert.equal(event.defaultPrevented, true);
		assert.ok(modal.classList.contains('show'));
	}
	modal.classList.remove('show');
	const slash = new dom.window.KeyboardEvent('keydown', { key: '/', bubbles: true, cancelable: true });
	draft.dispatchEvent(slash);
	assert.equal(slash.defaultPrevented, false);
	assert.ok(!modal.classList.contains('show'));
	search.value = 'Second';
	await client.filter();
	const result = dom.window.document.querySelector('[data-search-snippet="' + library.snippets[0].id + '"]');
	assert.ok(result, 'Search matches expansion text, not just the abbreviation');
	modal.classList.add('show');
	await client.onClick({ target: result });
	assert.equal(client.selected, library._id);
	assert.ok(!modal.classList.contains('show'));
	assert.ok(dom.window.document.querySelector('#form-modal').classList.contains('show'));
	assert.equal(dom.window.document.querySelector('#trigger').value, 'web');
	assert.equal(dom.window.document.querySelector('#replace').value, 'First\nSecond\n\n');
	dom.window.document.querySelector('#replace').value = 'Edited from search';
	await client.submit(new dom.window.FormData(dom.window.document.querySelector('#record-form')));
	assert.equal(client.libraries.get(library._id).snippets.find(entry => entry.id === library.snippets[0].id).replace, 'Edited from search');
	dom.window.document.querySelector('#form-modal').classList.remove('show');
	// Late search responses never replace a newer query.
	const request = client.request.bind(client);
	let finishOld;
	client.request = (path, ...args) => path === 'search?q=old' ? new Promise(resolve => { finishOld = resolve; }) : request(path, ...args);
	search.value = 'old';
	const old = client.filter();
	search.value = 'Second';
	await client.filter();
	const currentResults = dom.window.document.querySelector('#search-results').firstElementChild;
	finishOld('<p>Outdated response</p>');
	await old;
	assert.equal(dom.window.document.querySelector('#search-results').firstElementChild, currentResults);
	client.request = request;
	await client.editSnippet({ ...client.libraries.get(library._id), permissions: { edit: false } }, library.snippets[0].id);
	assert.equal(dom.window.document.querySelector('#trigger').readOnly, true);
	assert.equal(dom.window.document.querySelector('#record-form button[type="submit"]').disabled, true);
	await client.form('snippet', { library: library._id }, () => {});
	assert.equal(dom.window.document.querySelector('#record-form button[type="submit"]').disabled, false);
	const trigger = dom.window.document.querySelector('#trigger');
	assert.equal(trigger.parentElement.querySelector('.input-group-text').textContent, ',');
	trigger.value = ',,my-test';
	trigger.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
	assert.equal(trigger.value, 'my-test');
	assert.equal(trigger.checkValidity(), true);
	trigger.value = 'my,test';
	assert.equal(trigger.checkValidity(), false);
	trigger.value = ',tr';
	trigger.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
	assert.equal(trigger.value, 'tr');
	await client.snippet(undefined, { trigger: ',tr', replace: 'TypeRelay,\\nnext line' });
	const added = client.libraries.get(library._id).snippets.find(snippet => snippet.trigger === 'tr');
	assert.ok(added);
	assert.equal(added.replace, 'TypeRelay,\\nnext line');
	await assert.rejects(client.snippet(undefined, { trigger: ',tr', replace: 'Duplicate' }), /already exists|Duplicate/);
	await client.form('library', { library: library._id }, () => {});
	assert.ok(dom.window.document.querySelector('#shared'));
	const destination = (await Fixture.json('libraries', 'POST', { name: 'Bulk destination', yaml: 'matches: [{trigger: tr, replace: Collision}]' })).library;
	const moveEntry = client.libraries.get(library._id).snippets.find(entry => entry.trigger === 'tr');
	client.selectSnippet(moveEntry.id, true, false);
	await client.batchAction('move');
	dom.window.document.querySelector('#destination-library').value = destination._id;
	await assert.rejects(client.submit(new dom.window.FormData(dom.window.document.querySelector('#record-form'))), /already exists|Duplicate/);
	assert.equal(client.selectedSnippets.size, 1);
	assert.equal(dom.window.document.querySelector('#editor'), panel);
	await Fixture.json('snippets/batch', 'POST', { action: 'trash', source_library: destination._id, items: [{ id: destination.snippets[0].id, base_revision: destination.snippets[0].revision }] });
	await client.submit(new dom.window.FormData(dom.window.document.querySelector('#record-form')));
	assert.equal(client.selectedSnippets.size, 0);
	assert.ok(!dom.window.document.querySelector('#snippets [data-snippet="' + moveEntry.id + '"]'));
	assert.equal(client.libraries.get(destination._id).snippets[0].id, moveEntry.id);
	assert.equal(dom.window.document.querySelector('#editor'), panel);
	const edited = client.libraries.get(library._id).snippets.find(entry => entry.trigger === 'untouched');
	await client.editSnippet(client.libraries.get(library._id), edited.id);
	dom.window.document.querySelector('#destination-library').value = destination._id;
	dom.window.document.querySelector('#replace').value = 'Edited and moved';
	await client.submit(new dom.window.FormData(dom.window.document.querySelector('#record-form')));
	assert.equal(client.libraries.get(destination._id).snippets.find(entry => entry.id === edited.id).replace, 'Edited and moved');
	client.selectSnippet(library.snippets[0].id, true, false);
	await client.batchAction('trash');
	assert.equal(client.selectedSnippets.size, 0);
	assert.equal(client.libraries.get(library._id).snippets.length, 0);
	assert.equal(dom.window.document.querySelector('#editor'), panel);
	const list = dom.window.document.querySelector('#libraries');
	assert.ok(list.compareDocumentPosition(dom.window.document.querySelector('#import-menu')) & dom.window.Node.DOCUMENT_POSITION_FOLLOWING);
	assert.equal(dom.window.document.querySelectorAll('[data-import-format]').length, 5);
	await client.onClick({ target: dom.window.document.querySelector('[data-import-format="textexpander"]') });
	const importFile = dom.window.document.querySelector('#import-file');
	assert.equal(importFile.accept, '.csv');
	const exportText = 'abbreviation,snippet,label\nUPPER,"\tImported\ntext  ",Imported title\nBAD!,Skip,Skip\n';
	Object.defineProperty(importFile, 'files', { value: [{ name: 'UI beta.csv', size: exportText.length, text: async () => exportText }] });
	await client.onClick({ target: dom.window.document.querySelector('#preview-import') });
	assert.equal(dom.window.document.querySelectorAll('[data-import-entry]').length, 2);
	const correction = dom.window.document.querySelector('[data-import-trigger="0:0"]');
	assert.equal(correction.value, 'UPPER'); correction.value = 'beta-ui';
	const unselected = dom.window.document.querySelector('[data-import-key="0:1"]');
	unselected.checked = false; unselected.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
	assert.equal(dom.window.document.querySelector('[data-import-trigger="0:1"]').disabled, true);
	const oldCount = client.libraries.size;
	client.open = async () => { throw new Error('Import must not reload editor'); };
	await client.submit(new dom.window.FormData(dom.window.document.querySelector('#record-form')));
	assert.equal(client.libraries.size, oldCount + 1);
	assert.equal(dom.window.document.querySelector('#editor'), panel);
	const imported = [...client.libraries.values()].find(item => item.name === 'UI beta');
	assert.equal(imported.snippets[0].trigger, 'beta-ui');
	assert.equal(imported.snippets[0].replace, '\tImported\ntext  ');
	dom.window.close();
});
test('code imports sync to two desktops, preserve metadata offline and reject protocol 3', async () => {
	const text = '\t  {{ test }}\n $|$  \n\n';
	const source = { contents: { snippets: [{ title: 'Code sample', fragments: [{ content: text, language: 'RustLexer' }, { content: 'copy only\n', language: 'UnknownLexer' }] }] } };
	const preview = await Fixture.json('import/snippetslab/preview', 'POST', { source });
	assert.equal(preview.entries.length, 2);
	const body = { operation_id: randomUUID(), source, selected: [{ key: '0:0', trigger: 'codesample' }, { key: '0:1' }] };
	const imported = await Fixture.json('import/snippetslab', 'POST', body);
	assert.equal((await Fixture.json('import/snippetslab', 'POST', body)).libraries[0]._id, imported.libraries[0]._id);
	const library = imported.libraries[0];
	const one = await Fixture.device('code-one'); const two = await Fixture.device('code-two');
	await Fixture.cli(one, 'sync'); await Fixture.cli(two, 'sync');
	const first = (await Fixture.state(one)).libraries.find(item => item._id === library._id).records;
	assert.equal(first[0].content.text, text);
	assert.equal(first[1].trigger, null);
	await Fixture.edit(one, library.name, 'codesample', text + '\tupdated\n');
	await Fixture.cli(one, 'sync'); await Fixture.cli(two, 'sync');
	const records = (await Fixture.state(two)).libraries.find(item => item._id === library._id).records;
	assert.equal(records[0].content.language, 'RustLexer');
	assert.equal(records[0].title, 'Code sample — Fragment 1');
	assert.equal(records[0].content.text, text + '\tupdated\n');
	const credential = JSON.parse(await readFile(join(one.config, 'sync/credentials.json'), 'utf8'));
	const rejected = await fetch(Fixture.origin + '/api/v2/sync', { headers: { Authorization: 'Bearer ' + credential.access_token, 'X-TypeRelay-Sync-Protocol': '3' } });
	assert.equal(rejected.status, 426);
});

test('CSRF rejects writes, logout invalidates session', async () => {
	const response = await fetch(Fixture.origin + '/api/v2/libraries', { method: 'POST', headers: { Cookie: Fixture.cookie, 'Content-Type': 'application/json', 'X-Account-Id': Fixture.account }, body: JSON.stringify({ name: 'Blocked' }) });
	assert.equal(response.status, 403);
	assert.equal((await Fixture.request('/auth/logout', 'POST', {})).status, 200);
	assert.equal((await Fixture.request('/api/v2/libraries')).status, 403);
});
