import { test } from 'node:test';
import assert from 'node:assert/strict';

for (const custom of [false, true]) test(`browser sign-in captures callbacks and syncs images on the ${custom ? 'custom' : 'default'} server`, async () => {
	const values = () => {
		const data = {};
		return { get: async keys => Object.fromEntries((typeof keys === 'string' ? [keys] : keys).map(key => [key, data[key]])), set: async entries => Object.assign(data, entries), remove: async keys => { for (const key of typeof keys === 'string' ? [keys] : keys) delete data[key]; } };
	};
	const local = values();
	const session = values();
	const tabs = [];
	const removed = [];
	const cached = new Map();
	const assetId = 'a'.repeat(64);
	let messageListener;
	let updateListener;
	let installedListener;
	let optionsOpened = 0;
	const origin = custom ? 'https://custom.example.com' : 'https://app.typerelay.com';
	globalThis.chrome = { permissions: { contains: async ({ origins }) => origins[0] === `${origin}/*` }, storage: { local, session }, runtime: { onMessage: { addListener: listener => { messageListener = listener; } }, onInstalled: { addListener: listener => { installedListener = listener; } }, onStartup: { addListener: () => {} }, openOptionsPage: async () => { optionsOpened++; }, getPlatformInfo: async () => ({ os: 'cros' }) }, tabs: { create: async details => { tabs.push({ id: 10, ...details }); return tabs[0]; }, query: async () => tabs.filter(tab => tab.url.startsWith(`${origin}/oauth/browser-callback`)), remove: async id => { removed.push(id); tabs.splice(tabs.findIndex(tab => tab.id === id), 1); }, onUpdated: { addListener: listener => { updateListener = listener; } } }, alarms: { create: () => {}, onAlarm: { addListener: () => {} } } };
	globalThis.caches = { open: async () => ({ match: async key => cached.get(key), put: async (key, value) => { assert.match(new URL(key).protocol, /^https?:$/); cached.set(key, value); }, keys: async () => [...cached.keys()].map(url => ({ url })), delete: async key => cached.delete(key) }), delete: async () => true };
	globalThis.fetch = async url => {
		if (url === `${origin}/oauth/token`) return Response.json({ access_token: 'access', refresh_token: 'refresh', expires_in: 900, account: 'account' });
		if (url === `${origin}/api/v2/sync?cursor=0`) return Response.json({ protocol: 6, cursor: 'snapshot', libraries: [{ name: 'Test', state: 'active', snippets: [{ id: 'snippet', state: 'active', trigger: 'tr', title: 'Test result', content: { type: 'rich_text', markdown: 'Image', assets: [assetId] } }] }] });
		if (url === `${origin}/api/v2/assets/${assetId}`) return new Response(new Uint8Array([1, 2, 3]), { headers: { 'Content-Type': 'image/png' } });
		throw new Error(`Unexpected request: ${url}`);
	};
	await import(`../worker.js?auth-test=${Date.now()}`);
	const send = (type, data = {}) => new Promise(resolve => messageListener({ type, ...data }, {}, resolve));
	await installedListener({ reason: 'install' });
	assert.equal(optionsOpened, 1);
	await installedListener({ reason: 'update' });
	assert.equal(optionsOpened, 2);
	assert.equal((await send('connect', { origin: 'http://unsafe.example.com' })).ok, false);
	assert.equal((await send('connect', { origin: 'https://denied.example.com' })).ok, false);
	assert.deepEqual((await send('connect', { origin })).value, { pending: true });
	if (custom) assert.equal((await local.get('origin')).origin, origin);
	assert.equal(tabs.length, 1);
	const authorize = new URL(tabs[0].url);
	assert.equal(authorize.origin, origin);
	assert.equal(authorize.pathname, '/oauth/authorize');
	assert.equal(authorize.searchParams.get('redirect_uri'), `${origin}/oauth/browser-callback`);
	assert.equal(authorize.searchParams.get('code_challenge_method'), 'S256');
	const state = authorize.searchParams.get('state');
	const callback = `${origin}/oauth/browser-callback?code=one-time-code&state=${state}`;
	await session.set({ browserAuthError: 'Earlier sync failed' });
	updateListener(11, { url: `${origin}/oauth/browser-callback?code=wrong&state=wrong` });
	await new Promise(resolve => setImmediate(resolve));
	assert.equal((await local.get('tokens')).tokens, undefined);
	tabs.push({ id: 11, url: callback });
	updateListener(11, { url: callback });
	const status = await send('status');
	assert.equal(status.value.connected, true);
	assert.equal(status.value.origin, origin);
	assert.equal((await send('connect', { origin: 'https://another.example.com' })).ok, false);
	assert.equal(status.value.count, 1);
	assert.equal((await local.get('tokens')).tokens.access_token, 'access');
	assert.equal((await send('snapshot')).value.items[0].title, 'Test result');
	assert.ok(cached.has(`${origin}/api/v2/assets/${assetId}`));
	assert.equal((await session.get('browserAuthError')).browserAuthError, undefined);
	assert.deepEqual(removed, [11]);
	assert.equal((await session.get('browserAuth')).browserAuth, undefined);
	await installedListener({ reason: 'update' });
	assert.equal(optionsOpened, 2);
	await import(`../worker.js?restart=${custom}-${Date.now()}`);
	assert.equal((await send('status')).value.origin, origin);
});
