class Panel {
	constructor() {
		this.fillSequence=0; this.filling=null; this.rows=[]; this.index=0; this.sequence=0; this.busy=false;
		this.invoke=(name,args={})=>window.__TAURI__.core.invoke(name,args);
		this.aiSession=crypto.randomUUID();this.aiStatus=null;
		document.querySelector('#native-enable').onclick=()=>this.modelAction('download',document.querySelector('#native-enable'));
		document.querySelector('#native-cancel').onclick=()=>this.modelAction('cancel',document.querySelector('#native-cancel'));
		document.querySelector('#native-ai-enabled').onchange=event=>this.modelAction(event.target.checked?'enable':'disable',event.target);
		document.querySelector('#native-model').onchange=event=>{this.aiModel=event.target.value;this.modelInfo();if(this.aiStatus?.models.find(model=>model.id===this.aiModel)?.installed)void this.modelAction('enable',event.target);};
		void this.refreshAi();
		setInterval(()=>{if(!document.querySelector('#settings-advanced').hidden)void this.refreshAi();},1000);
		this.query=document.querySelector('#query');
		this.list=document.querySelector('#results');
		this.query.addEventListener('input',()=>{clearTimeout(this.timer);const sequence=++this.sequence;this.cancelAi();this.rows=[];this.render();this.timer=setTimeout(()=>this.search(sequence),0);this.aiTimer=setTimeout(()=>this.searchAi(sequence),600);});
		document.addEventListener('keydown',event=>{
			if(event.key==='Escape'){event.preventDefault();if(this.personalHit)this.closePersonal();else this.cancel();return;}
			if(this.personalHit)return;
			if(this.filling){if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();document.querySelector('#fill-form').requestSubmit();}return;}
			if(!document.querySelector('#settings-view').hidden)return;
			if(event.key.toLowerCase()==='c'&&(event.ctrlKey||event.metaKey)&&!event.altKey){if(this.rows.length||this.query.value){event.preventDefault();this.copy();}return;}
			if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();this.select(this.index+(event.key==='ArrowDown'?1:-1));}
			if(event.key==='Enter'){event.preventDefault();this.insert();}
		});
		document.querySelector('#personal-cancel').onclick=()=>this.closePersonal();
		document.querySelector('#personal-reset').onclick=()=>{document.querySelector('#personal-trigger').value='';};
		document.querySelector('#personal-use-pending').onclick=()=>{document.querySelector('#personal-trigger').value=this.personalInfo.personal.conflicts.find(row=>row.id===document.querySelector('#personal-conflict').value)?.trigger||'';};
		document.querySelector('#personal-use-rejected').onclick=()=>{document.querySelector('#personal-trigger').value=this.personalInfo.personal.rejected?.trigger||'';};
		document.querySelector('#personal-form').onsubmit=event=>{event.preventDefault();this.savePersonal();};
		document.querySelector('#copy').onclick=()=>this.copy();
		document.querySelector('#close').onclick=()=>this.cancel();
		document.querySelector('#open-settings').onclick=()=>this.action(()=>this.settings(true));
		document.querySelector('#fill-cancel').onclick=()=>this.cancel();
		document.querySelector('#fill-copy').onclick=()=>this.action(async()=>{const mode=this.fillMode;this.fillMode='copy';try{await this.commit();}finally{if(this.filling)this.fillMode=mode;}});
		document.querySelector('#fill-form').onsubmit=event=>{event.preventDefault();this.action(()=>this.commit());};
		document.querySelector('#fill-fields').oninput=()=>{clearTimeout(this.fillTimer);this.fillTimer=setTimeout(()=>this.previewFill(),80);};
		document.querySelector('#settings-cancel').onclick=()=>this.settings(false);
		for(const button of document.querySelectorAll('[data-settings-tab]'))button.onclick=()=>this.settingsPage(button.dataset.settingsTab);
		for(const button of document.querySelectorAll('[data-about-url]'))button.onclick=()=>this.action(()=>this.invoke('open_web_app',{url:button.dataset.aboutUrl}));
		document.querySelector('#settings-form').onsubmit=event=>{event.preventDefault();this.action(async()=>{await this.invoke('save_settings',{config:{shortcut:document.querySelector('#shortcut').value,launch_at_login:document.querySelector('#autostart').checked,keyboard:document.querySelector('#keyboard-setting').hidden?this.keyboard||'':document.querySelector('#keyboard').value}});await this.notify('Settings saved');});};
		document.querySelector('#open-accessibility').onclick=()=>this.action(async()=>{await this.invoke('open_accessibility_settings');await this.notify('Enable TypeRelay in Accessibility, then return here.');});
		document.querySelector('#open-notifications').onclick=()=>this.action(async()=>{await this.invoke('open_notification_settings');});
		document.querySelector('#open-input-monitoring').onclick=()=>this.action(async()=>{await this.invoke('open_input_monitoring_settings');await this.notify('Enable TypeRelay in Input Monitoring, then return here.');});
		document.querySelector('#open-tui').onclick=()=>this.action(()=>this.invoke('open_tui'));
		document.querySelector('#empty-sync').onclick=()=>this.action(async()=>{await this.settings(true);this.settingsPage('sync');});
		document.querySelector('#empty-web').onclick=()=>this.action(()=>this.invoke('open_web_app'));
		document.querySelector('#empty-tui').onclick=()=>this.action(()=>this.invoke('open_tui'));
		document.querySelector('#connect-form').onsubmit=event=>{event.preventDefault();void this.authenticate();};
		document.querySelector('#disconnect').onclick=()=>this.action(async()=>{const button=document.querySelector('#disconnect');button.disabled=true;try{await this.invoke('disconnect');this.connection('disconnected');this.cancelAi();await Promise.all([this.refreshLibraries(),this.refreshConflicts(),this.refreshPersonal()]);await this.notify('Disconnected');}finally{button.disabled=false;}});
		document.querySelector('#sync').onclick=()=>this.action(async()=>{if(this.connectionState!=='connected'||this.syncRunning)return;this.syncSubmitting=true;this.syncButton();try{const names=[...document.querySelectorAll('#local-libraries input:checked:not(:disabled)')].map(input=>input.value);if(names.length){await this.invoke('enroll',{names});await this.refreshLibraries();}await this.invoke('sync_now');}finally{this.syncSubmitting=false;this.syncButton();}});
		window.__TAURI__.event.listen('panel-error',event=>this.notify(event.payload,true));
		window.__TAURI__.event.listen('auth-state',event=>this.connection(event.payload.state,event.payload.message));
		window.__TAURI__.event.listen('sync-notice',async event=>{this.syncRunning=event.payload.running;this.syncButton();if(!event.payload.running){try{await Promise.all([this.refreshLibraries(),this.refreshConflicts(),this.refreshPersonal()]);}catch(error){this.notify(error,true);}}});
		window.__TAURI__.event.listen('panel-open',event=>this.open(event.payload));
		window.addEventListener('focus',()=>{if(document.body.dataset.os==='macos')this.refreshPermissions();});
		this.invoke('initialize').then(value=>{this.configure(value);this.open(value);}).catch(error=>this.notify(error,true));
	}
	configure(value){document.querySelector('#shortcut').value=value.config.shortcut;document.querySelector('#autostart').checked=value.config.launch_at_login;this.configureKeyboard(value);if(value.server)document.querySelector('#server').value=value.server;if(value.version)document.querySelector('#app-version').textContent='Version '+value.version;this.connection(value.connection_state||(value.connected?'connected':'disconnected'),value.auth_error);this.empty=!!value.empty;for(const [name,allowed]of[['accessibility',!!value.accessibility],['input-monitoring',!!value.input_monitoring]]){const card=document.querySelector('#'+name+'-card');const state=document.querySelector('#'+name+'-state');state.textContent=allowed?'Approved':'Required';state.dataset.allowed=String(allowed);card.hidden=false;card.querySelector('button').hidden=allowed;}const notifications=document.querySelector('#notifications-state');notifications.textContent=value.notifications===true?'Enabled':value.notifications===false?'Disabled':'Unavailable';notifications.dataset.allowed=String(value.notifications===true);this.render();}
	configureKeyboard(value){this.keyboard=value.config.keyboard||'';const keyboardSetting=document.querySelector('#keyboard-setting');keyboardSetting.hidden=value.theme?.os!=='linux';document.querySelector('#keyboard-card').hidden=keyboardSetting.hidden;const select=document.querySelector('#keyboard');const existing=new Map([...select.options].filter(option=>option.value).map(option=>[option.value,option]));const names=new Set(value.keyboards||[]);if(this.keyboard)names.add(this.keyboard);for(const name of names){let option=existing.get(name);if(!option){option=document.querySelector('#keyboard-option-template').content.firstElementChild.cloneNode(true);option.value=name;select.append(option);}option.textContent=name+(value.keyboards?.includes(name)?'':' (disconnected)');existing.delete(name);}for(const option of existing.values())option.remove();select.value=this.keyboard;}
	syncButton(){const button=document.querySelector('#sync');const running=this.syncRunning||this.syncSubmitting;button.disabled=!!running||this.connectionState!=='connected';button.textContent=running?'Syncing…':'Sync now';}
	connection(state,message=''){this.connectionState=state;const authenticate=document.querySelector('#authenticate');const server=document.querySelector('#server');const status=document.querySelector('#connection-status');authenticate.textContent=state==='authenticating'?'Cancel authentication':'Authenticate';authenticate.disabled=state==='connected';server.disabled=state==='authenticating'||state==='connected';status.textContent=state==='connected'?'':message||(state==='authenticating'?'Waiting for browser sign-in…':'Not connected');status.hidden=!status.textContent;status.setAttribute('role',state==='disconnected'&&message?'alert':'status');document.querySelector('#disconnect').hidden=state!=='connected';this.syncButton();}
	async authenticate(){if(this.connectionState==='authenticating'){await this.invoke('cancel_connect');this.connection('authenticating','Cancelling authentication…');document.querySelector('#authenticate').disabled=true;return;}if(this.connectionState==='connected')return;this.connection('authenticating','Complete sign-in in any browser.');try{await this.invoke('connect',{url:document.querySelector('#server').value});this.connection('connected','Connected');await this.refreshLibraries();await this.notify('Connected');}catch(error){const message=this.statusMessage(error);this.connection('disconnected',message==='Authentication cancelled'?'Authentication cancelled.':message);if(message!=='Authentication cancelled')await this.notify(message,true);}}
	async notify(value,error=false){const message=this.statusMessage(value);if(!message)return;this.lastStatus=message;try{await this.invoke('notify',{message,error});}catch(failure){console.error('Native notification failed',failure);}}
	async reportStatus(value){const message=this.statusMessage(value);if(!message){this.lastStatus='';return;}if(message!==this.lastStatus)await this.notify(message,true);}
	statusMessage(value){const status=String(value||'').replace(/^Error:\s*/, '').trim();return /^Choose (?:another|an) (?:app|application)\b/i.test(status)?'':status;}
	async refreshPermissions(){try{const value=await this.invoke('initialize');this.configure(value);await this.reportStatus(value.status);}catch(error){this.notify(error,true);}}
	settingsPage(name){this.settingsTab=name;for(const button of document.querySelectorAll('[data-settings-tab]'))button.setAttribute('aria-selected',String(button.dataset.settingsTab===name));for(const page of document.querySelectorAll('.settings-page'))page.hidden=page.id!=='settings-'+name;}
	async open(value){this.cancelAi();void this.refreshAi();this.personalHit=null;document.querySelector('#personal-view').hidden=true;this.filling=null;document.querySelector('#fill-view').hidden=true;document.querySelector('#fill-fields').replaceChildren();this.sequence++;this.query.value='';this.rows=[];this.render();await this.reportStatus(value.status);document.body.dataset.os=value.theme?.os||'';for(const key of ['background','foreground','accent']){if(/^#[0-9a-f]{6}$/i.test(value.theme?.[key]||''))document.body.style.setProperty('--'+key,value.theme[key]);}await this.settings(!!value.settings);if(value.prompt)await this.action(()=>this.start(value.prompt,'insert'));}
	async settings(visible){if(visible)this.cancelAi();await this.invoke('set_settings_view',{enabled:visible});document.body.dataset.view=visible?'settings':'search';document.querySelector('#window-title').textContent=visible?'Settings':'TypeRelay';document.querySelector('#settings-view').hidden=!visible;document.querySelector('#search-view').hidden=visible;if(visible){this.settingsPage(this.settingsTab||'general');try{const value=await this.invoke('initialize');this.configure(value);await Promise.all([this.refreshLibraries(),this.refreshConflicts(),this.refreshPersonal()]);}catch(error){this.notify(error,true);}}else{this.query.focus();}}
	async refreshLibraries(){const sequence=this.librarySequence=(this.librarySequence||0)+1;const rows=await this.invoke('libraries');if(sequence!==this.librarySequence)return;const container=document.querySelector('#local-libraries');const existing=new Map([...container.children].map(node=>[node.dataset.id,node]));for(const library of rows){let node=existing.get(library.id);if(!node){node=document.querySelector('#library-template').content.firstElementChild.cloneNode(true);node.dataset.id=library.id;container.append(node);}existing.delete(library.id);node._library=library;const input=node.querySelector('input');input.value=library.name;input.hidden=library.synced;input.disabled=library.synced||library.merge_pending;if(library.synced||library.merge_pending)input.checked=false;node.querySelector('.library-name').textContent=library.name+' ('+library.snippets+')';const state=node.querySelector('.library-sync-state');state.textContent=library.merge_pending?'Merge pending':library.synced?'Synced':'Local only';state.dataset.allowed=String(library.synced&&!library.merge_pending);const merge=node.querySelector('.library-merge');merge.hidden=!library.can_merge;merge.disabled=library.merge_pending;merge.onclick=()=>this.action(()=>this.openMerge(node));node.querySelector('.library-merge-cancel').onclick=()=>{node.querySelector('.library-merge-form').hidden=true;};node.querySelector('.library-merge-submit').onclick=event=>this.action(()=>this.mergeLibrary(node,event.currentTarget));}for(const node of existing.values())node.remove();}
	async openMerge(node){const rows=await this.invoke('merge_destinations',{source:node.dataset.id});if(!rows.length)throw Error('No eligible destination. Upload a local destination before merging a synced library into it.');const select=node.querySelector('.library-merge-destination');select.replaceChildren();for(const library of rows){const option=document.querySelector('#merge-option-template').content.firstElementChild.cloneNode(true);option.value=library.id;option.textContent=library.name+' · '+library.snippets+' snippets · '+(library.synced?'Synced':'Local only');select.append(option);}node.querySelector('.library-merge-form').hidden=false;select.focus();}
	async mergeLibrary(node,button){const destination=node.querySelector('.library-merge-destination').value;const option=node.querySelector('.library-merge-destination').selectedOptions[0];if(!destination)throw Error('Choose a destination');const confirmed=await Swal.fire({title:'Merge library?',text:`Move ${node._library.snippets} snippets from ${node._library.name} into ${option.textContent}? Destination sharing applies. The source moves to Trash after success.`,icon:'warning',showCancelButton:true,confirmButtonText:'Merge library',reverseButtons:true});if(!confirmed.isConfirmed)return;if(button)button.disabled=true;try{const result=await this.invoke('merge_library',{source:node.dataset.id,destination});await this.refreshLibraries();await this.notify(result.queued?'Merge queued':'Libraries merged');}finally{if(button?.isConnected)button.disabled=false;}}
	async refreshConflicts(){const sequence=this.conflictSequence=(this.conflictSequence||0)+1;const rows=await this.invoke('conflicts');if(sequence!==this.conflictSequence)return;const section=document.querySelector('#conflict-section');const container=document.querySelector('#sync-conflicts');section.hidden=!rows.length;document.querySelector('#conflict-count').textContent=rows.length+' conflict'+(rows.length===1?'':'s')+' preserved. Review each record before resolving.';const existing=new Map([...container.children].map(node=>[node.dataset.id,node]));for(const conflict of rows){let node=existing.get(conflict._id);if(!node){node=document.querySelector('#conflict-template').content.firstElementChild.cloneNode(true);node.dataset.id=conflict._id;container.append(node);}existing.delete(conflict._id);node._conflict=conflict;node.querySelector('.conflict-open').textContent=(conflict.library_name||'Library')+' · '+(conflict.local?.title||conflict.server?.title||conflict.local?.trigger||conflict.server?.trigger||'Deleted record');node.querySelector('.conflict-open').onclick=()=>this.openConflict(node);node.querySelector('.conflict-cancel').onclick=()=>{node.querySelector('.conflict-detail').hidden=true;};node.querySelector('.conflict-form').onsubmit=event=>{event.preventDefault();void this.resolveConflict(node,event.submitter);};}for(const node of existing.values())node.remove();}
	openConflict(node){const conflict=node._conflict;for(const side of ['base','local','server'])node.querySelector('.conflict-'+side).textContent=conflict[side]?JSON.stringify(conflict[side],null,2):'Deleted';const source=conflict.local||conflict.server||conflict.base||{};const content=source.content||{};node._mergeSource=source;node.querySelector('.conflict-title').value=source.title||'';node.querySelector('.conflict-trigger').value=source.trigger||'';node.querySelector('.conflict-type').value=content.type||'plain_text';node.querySelector('.conflict-body').value=content.type==='rich_text'?(content.markdown||''):(content.text||'');node.querySelector('.conflict-language').value=content.language||'';node.querySelector('.conflict-choice').value='merged';node.querySelector('.conflict-choice').onchange=()=>this.conflictFields(node);this.conflictFields(node);node.querySelector('.conflict-detail').hidden=false;}
	conflictFields(node){const disabled=node.querySelector('.conflict-choice').value!=='merged';for(const field of node.querySelectorAll('.conflict-title,.conflict-trigger,.conflict-type,.conflict-body,.conflict-language'))field.disabled=disabled;}
	async resolveConflict(node,button){if(button)button.disabled=true;try{const choice=node.querySelector('.conflict-choice').value;let value=null;if(choice==='merged'){const source=node._mergeSource||{};const type=node.querySelector('.conflict-type').value;const content=JSON.parse(JSON.stringify(source.content||{}));content.version=type==='rich_text'?2:1;content.type=type;if(type==='rich_text'){content.markdown=node.querySelector('.conflict-body').value;delete content.text;delete content.language;}else{content.text=node.querySelector('.conflict-body').value;delete content.markdown;delete content.assets;if(type==='code')content.language=node.querySelector('.conflict-language').value||'plain_text';else delete content.language;}value={title:node.querySelector('.conflict-title').value,trigger:node.querySelector('.conflict-trigger').value,content};}await this.invoke('resolve_conflict',{id:node.dataset.id,choice,value});node.remove();await Promise.all([this.refreshLibraries(),this.refreshConflicts(),this.refreshPersonal()]);await this.notify('Conflict resolved');}catch(error){await this.notify(error,true);}finally{if(button?.isConnected)button.disabled=false;}}

	async search(sequence){try{const rows=await this.invoke('search',{query:this.query.value});if(sequence!==this.sequence||this.aiApplied===sequence)return;this.rows=rows;this.index=0;this.render();}catch(error){if(sequence===this.sequence)this.notify(error,true);}}
	render(){const selected=this.rows[this.index];const scroll=this.list.scrollTop;const nodes=new Map([...this.list.children].map(node=>[node.dataset.key,node]));document.querySelector('#empty-state').hidden=!this.empty;document.querySelector('#hint').hidden=this.empty||!!this.rows.length;document.querySelector('#hint').textContent=this.query.value?'No matching snippets.':'Type an abbreviation or describe a saved snippet.';for(const [index,row] of this.rows.entries()){const key=row.library+':'+row.id;let node=nodes.get(key);if(!node){node=document.querySelector('#result-template').content.firstElementChild.cloneNode(true);node.dataset.key=key;}nodes.delete(key);node.querySelector('.result-title').textContent=row.title||row.abbreviation||'Untitled snippet';node.querySelector('.result-library').textContent=row.library_name;node.querySelector('.result-abbreviation').textContent=row.abbreviation;node.querySelector('.result-preview').textContent=row.preview;node.querySelector('.result-personal').hidden=!row.can_personal&&!row.review_personal;node.querySelector('.result-personal').textContent=row.can_personal?'My abbreviation':'Review abbreviation';node.querySelector('.result-personal').onclick=event=>{event.stopPropagation();this.action(()=>this.openPersonal(row));};node.querySelector('.result-personal-status').textContent=this.personalStatus(row);node.onclick=()=>{this.select(index);this.insert();};node.setAttribute('aria-selected',String(row===selected));const at=this.list.children[index];if(at!==node)this.list.insertBefore(node,at||null);}for(const node of nodes.values())node.remove();this.list.scrollTop=scroll;document.querySelector('#copy').disabled=!this.rows.length;}
	cancelAi(){clearTimeout(this.aiTimer);if(this.aiRequest){void this.invoke('native_ai',{request:{op:'cancel',id:this.aiRequest}}).catch(()=>{});this.aiRequest=null;}}
	async searchAi(sequence){const query=this.query.value;if(sequence!==this.sequence||!query.trim()||this.rows.some(row=>row.abbreviation.toLowerCase()===query.trim().toLowerCase())||!this.aiStatus?.model)return;const id=this.aiSession+':'+sequence;this.aiRequest=id;try{const rows=await this.invoke('native_ai',{request:{op:'search',query,id}});if(sequence!==this.sequence||this.aiRequest!==id||this.filling||this.personalHit||!document.querySelector('#settings-view').hidden)return;const selected=this.rows[this.index];this.aiApplied=sequence;this.rows=rows;this.index=Math.max(0,rows.findIndex(row=>row.id===selected?.id&&row.library===selected?.library));this.render();}catch{}finally{if(this.aiRequest===id)this.aiRequest=null;}}
	async refreshAi(force=false){if(this.aiRefreshing&&!force)return;this.aiRefreshing=true;const sequence=this.aiRefreshSequence=(this.aiRefreshSequence||0)+1;try{const status=await this.invoke('native_ai',{request:{op:'status'}});if(sequence!==this.aiRefreshSequence)return;this.aiStatus=status;const container=document.querySelector('#native-model');for(const model of status.models){let row=[...container.children].find(row=>row.dataset.id===model.id);if(!row){row=document.querySelector('#native-model-option').content.firstElementChild.cloneNode(true);row.dataset.id=model.id;row.querySelector('input').value=model.id;row.querySelector('.native-model-name').textContent=model.name;row.querySelector('.native-model-recommended').hidden=!model.recommended;row.querySelector('.native-model-size').textContent=(model.bytes/1e9).toFixed(2)+' GB';row.querySelector('.native-model-description').textContent=model.recommended?'Best balance of speed and quality':model.bytes<status.models.find(model=>model.recommended)?.bytes?'Lightweight option for less powerful Macs':'Higher quality option for more powerful Macs';container.append(row);}}if(!this.aiModel)this.aiModel=status.model||status.models.find(model=>model.recommended)?.id;this.modelInfo();}catch(error){document.querySelector('#native-ai-status').textContent=String(error);}finally{if(sequence===this.aiRefreshSequence)this.aiRefreshing=false;}}
	modelInfo(){if(!this.aiStatus)return;const model=this.aiStatus.models.find(model=>model.id===this.aiModel);const enabled=this.aiStatus.enabled??!!this.aiStatus.model;const busy=!!this.aiAction||!!this.aiStatus.download;const checkbox=document.querySelector('#native-ai-enabled');checkbox.checked=this.aiToggle??enabled;checkbox.disabled=busy;document.querySelector('#native-ai-card').hidden=!checkbox.checked;for(const row of document.querySelector('#native-model').children){const input=row.querySelector('input');input.checked=row.dataset.id===this.aiModel;input.disabled=busy;row.dataset.selected=String(input.checked);}if(!model)return;const downloading=!!this.aiStatus.download||this.aiAction==='download';const progress=document.querySelector('#native-download');progress.hidden=!downloading;progress.value=model.downloaded/model.bytes*100;document.querySelector('#native-cancel').hidden=!this.aiStatus.download;const button=document.querySelector('#native-enable');button.textContent='Download '+(model.bytes/1e9).toFixed(2)+' GB Model';button.disabled=busy;button.hidden=model.installed||downloading;document.querySelector('#native-download-area').hidden=model.installed&&!downloading;document.querySelector('#native-download-label').textContent=downloading?'Downloading…':'Download to continue';document.querySelector('#native-ai-status').textContent=this.aiStatus.error||(this.aiAction==='enable'?'Enabling…':'');}
	async modelAction(op,button){if(this.aiAction&&op!=='cancel')return;const model=this.aiStatus?.models.find(model=>model.id===this.aiModel);if(!model)return;const toggle=button.id==='native-ai-enabled';if(op==='enable'&&!toggle&&this.aiStatus.model===model.id)return;if(op==='download'){const consent=await Swal.fire({title:'Download '+model.name+'?',text:(model.bytes/1e9).toFixed(2)+' GB. Apache 2.0. AI runs only on this device.',showCancelButton:true,confirmButtonText:'Download '+(model.bytes/1e9).toFixed(2)+' GB Model'});if(!consent.isConfirmed)return;if(this.aiAction)return;}this.cancelAi();if(toggle)this.aiToggle=button.checked;if(op!=='cancel')this.aiAction=op;button.disabled=true;this.modelInfo();try{await this.invoke('native_ai',{request:{op,model:op==='enable'&&!model.installed?null:model.id,id:op==='cancel'?this.aiStatus.download:crypto.randomUUID()}});}catch(error){if(op==='enable'&&!toggle&&this.aiStatus.model)this.aiModel=this.aiStatus.model;await Swal.fire({toast:true,position:'top-end',icon:'error',title:String(error),showConfirmButton:false,timer:5000});}finally{await this.refreshAi(true);if(op!=='cancel'){this.aiAction=null;this.aiToggle=null;}button.disabled=false;this.modelInfo();}}
	async refreshPersonal(){if(!this.rows.length)return;const sequence=this.sequence;const version=this.personalVersion;const rows=await this.invoke('personal_status',{hits:this.rows});if(sequence!==this.sequence||version!==this.personalVersion||!rows)return;for(const row of rows){const index=this.rows.findIndex(item=>item.id===row.id&&item.library===row.library);if(index<0)continue;const previous=this.rows[index];if((previous.personal?.revision||0)>(row.personal?.revision||0))continue;Object.assign(previous,row);const node=this.list.children[index];node.querySelector('.result-abbreviation').textContent=row.abbreviation||'';node.querySelector('.result-personal-status').textContent=this.personalStatus(row);node.querySelector('.result-personal').hidden=!row.can_personal&&!row.review_personal;}if(this.personalHit){const latest=rows.find(row=>row.id===this.personalHit.id&&row.library===this.personalHit.library);if(latest){document.querySelector('#personal-status').textContent=this.personalStatus(latest);if(!latest.can_personal)document.querySelector('#personal-save').disabled=true;}}}
	personalStatus(row){return row.abbreviation_collision?'Abbreviation paused: duplicate':row.personal?.conflicts?.length?'Personal abbreviation conflict':row.personal?.rejected?'Personal change rejected — review':row.personal?.pending?'Abbreviation waiting to sync':'';}
	async openPersonal(hit){const info=await this.invoke('personal_abbreviation',{hit});this.personalHit=hit;this.personalInfo=info;document.querySelector('#search-view').hidden=true;document.querySelector('#personal-view').hidden=false;document.querySelector('#personal-shared').textContent='Shared abbreviation: '+(info.shared_trigger||'None');document.querySelector('#personal-trigger').value=info.personal.trigger||'';document.querySelector('#personal-status').textContent=this.personalStatus({...hit,personal:info.personal});document.querySelector('#personal-save').disabled=!!info.personal.pending||info.can_edit===false;for(const id of ['personal-trigger','personal-reset','personal-use-pending','personal-use-rejected'])document.querySelector('#'+id).disabled=info.can_edit===false;if(info.can_edit===false)document.querySelector('#personal-status').textContent+=' · Editing permission required to change this abbreviation';const select=document.querySelector('#personal-conflict');select.replaceChildren();for(const conflict of info.personal.conflicts||[]){const option=document.createElement('option');option.value=conflict.id;option.textContent='Pending: '+(conflict.trigger||'Shared default');select.append(option);}for(const id of ['personal-conflict','personal-conflict-label','personal-use-pending'])document.querySelector('#'+id).hidden=!select.options.length;document.querySelector('#personal-use-rejected').hidden=!info.personal.rejected;document.querySelector('#personal-trigger').focus();}
	closePersonal(){this.personalHit=null;document.querySelector('#personal-view').hidden=true;document.querySelector('#search-view').hidden=false;this.query.focus({preventScroll:true});}
	async savePersonal(){this.personalVersion=(this.personalVersion||0)+1;const button=document.querySelector('#personal-save');button.disabled=true;try{const hit=this.personalHit;const info=await this.invoke('personal_abbreviation',{hit,change:{trigger:document.querySelector('#personal-trigger').value||null,base_revision:this.personalInfo.personal.revision,conflict:document.querySelector('#personal-conflict').value||null}});hit.personal=info.personal;hit.abbreviation=info.personal.trigger??info.shared_trigger??'';const index=this.rows.findIndex(row=>row.id===hit.id&&row.library===hit.library);if(index>=0){this.rows[index]=hit;const node=this.list.children[index];node.querySelector('.result-abbreviation').textContent=hit.abbreviation;node.querySelector('.result-personal-status').textContent=this.personalStatus(hit);}this.personalVersion++;this.closePersonal();await this.refreshPersonal();await this.notify('Personal abbreviation saved; waiting to sync');}catch(error){await this.notify(error,true);}finally{button.disabled=false;}}
	select(index){this.index=Math.max(0,Math.min(index,this.rows.length-1));[...this.list.children].forEach((node,i)=>{node.setAttribute('aria-selected',String(i===this.index));if(i===this.index)node.scrollIntoView({block:'nearest'});});document.querySelector('#copy').disabled=!this.rows.length;}
	async action(action){if(this.busy)return;this.busy=true;try{await action();}catch(error){await this.notify(error,true);}finally{this.busy=false;}}
	activate(mode){this.action(async()=>{const sequence=this.sequence;if(!this.rows.length&&this.query.value){clearTimeout(this.timer);await this.search(sequence);}if(sequence===this.sequence&&this.rows.length)await this.start(this.rows[this.index],mode);});}
	insert(){this.activate('insert');}
	copy(){this.activate('copy');}
	cancel(){this.cancelAi();this.filling=null;document.querySelector('#fill-fields').replaceChildren();document.querySelector('#fill-preview').textContent='';this.invoke('dismiss');}
	answers(){return Object.fromEntries([...document.querySelectorAll('[data-answer]')].map(field=>[field.dataset.answer,field.value]));}
	async start(hit,mode){
		this.cancelAi();
		if(!hit)return;
		const result=await this.invoke('prepare_template',{hit});
		this.filling=hit;this.fillMode=mode;this.enterActions=result.enter_actions;
		if(!result.fields.length){await this.commit();return;}
		await this.invoke('set_prompt_view',{enabled:true});
		document.querySelector('#search-view').hidden=true;document.querySelector('#settings-view').hidden=true;document.querySelector('#fill-view').hidden=false;
		const container=document.querySelector('#fill-fields');container.replaceChildren();
		for(const name of result.fields){const field=result.template.variables[name];const row=document.querySelector('#fill-field').content.firstElementChild.cloneNode(true);const input=row.querySelector(field.multiline?'textarea':'input');row.querySelector('input').hidden=field.multiline;row.querySelector('textarea').hidden=!field.multiline;input.id='fill-'+name;input.dataset.answer=name;input.value=field.default;input.required=field.required;row.querySelector('label').htmlFor=input.id;row.querySelector('label').textContent=field.label+(field.required?' *':'');container.append(row);}
		document.querySelector('#fill-submit').textContent=mode==='copy'?'Copy filled text':'Insert';document.querySelector('#fill-copy').hidden=mode==='copy';
		document.querySelector('#fill-actions').textContent=result.enter_actions?(mode==='copy'?'Copy omits Enter key actions.':'Includes '+result.enter_actions+' Enter keypress(es).'):'';
		await this.previewFill();container.querySelector('[data-answer]')?.focus();
	}
	async previewFill(){const hit=this.filling;if(!hit)return;const sequence=++this.fillSequence;try{const result=await this.invoke('prepare_template',{hit,values:this.answers()});if(this.filling!==hit||sequence!==this.fillSequence)return;document.querySelector('#fill-preview').textContent=result.steps.map(step=>step.kind==='enter'?'⏎ [Enter key]':step.text).join('');}catch(error){await this.reportStatus(error);}}
	async commit(){const hit=this.filling;if(!hit)return;const values=this.answers();await this.invoke(this.fillMode==='copy'?'copy_snippet':'insert',{hit,values});const copied=this.fillMode==='copy';this.filling=null;document.querySelector('#fill-fields').replaceChildren();document.querySelector('#fill-view').hidden=true;await this.invoke('set_prompt_view',{enabled:false});if(copied){document.querySelector('#search-view').hidden=false;await this.notify(this.enterActions?'Copied text; Enter key actions omitted.':'Copied');}}

}
new Panel();
