export class AiSchema {
	static specification() {
		const scope = { enum: ['personal', 'team'], default: 'personal' };
		const protocol = { enum: ['auto', 'chat', 'responses', 'anthropic', 'gemini'], default: 'auto' };
		const route = { type: 'object', required: ['connection', 'model'], properties: { connection: { type: 'string' }, model: { type: 'string', maxLength: 200 }, protocol } };
		const requestId = { type: 'string', pattern: '^[a-zA-Z0-9-]{16,80}$', description: 'New UUID per deliberate action. Replays return 409. Metadata is retained for three days.' };
		const selected = { scope, connection: { type: 'string' }, model: { type: 'string', maxLength: 200 }, protocol };
		const paths = {};
		const add = (path, method, summary, properties, required = [], parameters = []) => { paths[path] ||= {}; paths[path][method] = { summary, tags: ['First-party AI'], parameters, ...(properties ? { requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties, required } } } } } : {}), responses: { 200: { description: 'Result; settings contain masked key status. HTML fields are Pug fragments.' }, 400: { description: 'Invalid input' }, 401: { description: 'Authentication required' }, 403: { description: 'AI disabled, permission denied, or managed AI requires Pro/Team' }, 404: { description: 'Connection/library unavailable' }, 409: { description: 'Stale settings or replayed action' }, 422: { description: 'Missing provider/model, unapproved endpoint, or invalid content' }, 429: { description: 'Managed allowance or request rate reached' }, 502: { description: 'Provider failure or invalid/incomplete proposal' }, 504: { description: 'Provider timeout' } } }; };
		add('/settings', 'get', 'Read effective status or scoped settings', null, [], [{ in: 'query', name: 'scope', schema: scope, description: 'Omit for effective status; team configuration requires owner/admin.' }]);
		add('/settings', 'patch', 'Save personal/team policy and routes', { scope, enabled: { type: 'boolean' }, revision: { type: 'integer' }, routes: { type: 'object', properties: { authoring: route, search: route } } }, ['enabled']);
		add('/connections', 'post', 'Create/update an encrypted connection', { scope, revision: { type: 'integer' }, id: { type: 'string', description: 'Omit to create; provide a saved ID to update.' }, name: { type: 'string', maxLength: 100 }, provider: { enum: ['openai', 'google', 'gemini', 'anthropic', 'openrouter', 'opencode', 'compatible'] }, api_key: { type: 'string', maxLength: 4096, writeOnly: true, description: 'Blank preserves a saved key; keys are never returned.' }, clear_key: { type: 'boolean' }, base_url: { type: 'string', format: 'uri' }, no_auth: { type: 'boolean' } }, ['name', 'provider']);
		add('/connections/{id}', 'delete', 'Remove a scoped connection', { scope, revision: { type: 'integer' } }, [], [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }]);
		add('/models', 'post', 'Discover model IDs/names using a saved connection', selected, ['connection']);
		add('/verify', 'post', 'Verify a model with a small generation request', selected, ['connection', 'model']);
		add('/author', 'post', 'Return a validated unsaved snippet proposal', { request_id: requestId, action: { enum: ['generate', 'improve', 'translate', 'template'] }, prompt: { type: 'string', minLength: 1, maxLength: 4000 }, library: { type: 'string', description: 'Requires edit permission when supplied.' }, entry: { type: 'object', required: ['content'], properties: { title: { type: 'string' }, trigger: { type: ['string', 'null'] }, content: { type: 'object', description: 'Existing Typerelay Text, Code, Template, or Rich text content.' } } } }, ['request_id', 'action', 'prompt', 'entry']);
		add('/search', 'post', 'Return up to ten existing snippet references', { request_id: requestId, query: { type: 'string', minLength: 1, maxLength: 4000 }, libraries: { type: 'array', maxItems: 256, items: { type: 'string' } }, local: { type: 'array', maxItems: 20000, description: 'Explicitly selected local-only records; at most 8 MiB combined, never synchronized or persisted.', items: { type: 'object', required: ['id', 'library', 'revision', 'text'], properties: { id: { type: 'string', maxLength: 100 }, library: { type: 'string', maxLength: 100 }, revision: { type: 'integer' }, title: { type: 'string' }, library_name: { type: 'string' }, trigger: { type: 'string' }, text: { type: 'string', maxLength: 65536 } } } } }, ['request_id', 'query']);
		return { openapi: '3.1.0', info: { title: 'Typerelay first-party AI API', version: '1.0.0', description: 'Separate from public REST/MCP. Web sessions require X-Account-Id and mutation CSRF headers. Device bearer requests require X-TypeRelay-Sync-Protocol: 6. Credentials stay on the server. Managed AI defaults to 50 actions per Pro/Team user per UTC day.' }, servers: [{ url: '/api/v2/ai' }], security: [{ Device: [] }, { Session: [] }], paths, components: { securitySchemes: { Device: { type: 'http', scheme: 'bearer' }, Session: { type: 'apiKey', in: 'cookie', name: 'connect.sid', description: 'Mutation requests require X-CSRF-Token.' } } } };
	}
}
