// One catalog drives API routing, OpenAPI operations, and the MCP content adapter.
export const scopes = ['content:read', 'content:write', 'sharing:write', 'trash:purge', 'team:read', 'team:write', 'devices:read', 'devices:write'];
export const operations = [
	['get', '/me', 'get_identity', 'content:read', 'Account', 'Get integration identity', false],
	['get', '/libraries', 'list_libraries', 'content:read', 'Libraries', 'List libraries'],
	['get', '/libraries/:id', 'get_library', 'content:read', 'Libraries', 'Get library'],
	['post', '/libraries', 'create_library', 'content:write', 'Libraries', 'Create private library'],
	['patch', '/libraries/:id', 'update_library', 'sharing:write', 'Libraries', 'Rename library or update sharing'],
	['get', '/libraries/:id/snippets', 'list_snippets', 'content:read', 'Snippets', 'List snippets'],
	['get', '/libraries/:id/snippets/:snippet', 'get_snippet', 'content:read', 'Snippets', 'Get snippet'],
	['post', '/libraries/:id/snippets', 'create_snippet', 'content:write', 'Snippets', 'Create snippet'],
	['patch', '/libraries/:id/snippets/:snippet', 'update_snippet', 'content:write', 'Snippets', 'Edit snippet'],
	['post', '/snippets/batch', 'batch_snippets', 'content:write', 'Snippets', 'Move or trash snippets atomically'],
	['get', '/search', 'search_snippets', 'content:read', 'Search', 'Search accessible snippets'],
	['get', '/libraries/:id/export', 'export_library', 'content:read', 'Import and export', 'Export library as YAML'],
	['post', '/imports/:format/preview', 'preview_import', 'content:write', 'Import and export', 'Preview import'],
	['post', '/imports/:format', 'commit_import', 'content:write', 'Import and export', 'Import into new private libraries'],
	['get', '/trash', 'list_trash', 'content:read', 'Trash', 'List accessible Trash'],
	['post', '/trash/action', 'change_trash', 'content:write', 'Trash', 'Trash or restore an item'],
	['post', '/trash/purge', 'purge_item', 'trash:purge', 'Trash', 'Permanently purge a trashed item'],
	['post', '/trash/empty', 'empty_trash', 'trash:purge', 'Trash', 'Permanently purge an explicit Trash selection'],
	['get', '/conflicts', 'list_conflicts', 'content:write', 'Conflicts', 'List editable conflicts'],
	['post', '/conflicts/:id', 'resolve_conflict', 'content:write', 'Conflicts', 'Resolve conflict'],
	['get', '/operations/:id', 'get_operation', 'content:read', 'Operations', 'Get operation receipt'],
	['get', '/team', 'get_team', 'team:read', 'Team', 'List team and groups', false],
	['post', '/team/groups', 'create_group', 'team:write', 'Team', 'Create group', false],
	['patch', '/team/groups/:id', 'update_group', 'team:write', 'Team', 'Update or remove group', false],
	['patch', '/team/members/:id', 'update_member', 'team:write', 'Team', 'Change role or remove member', false],
	['get', '/devices', 'list_devices', 'devices:read', 'Devices', 'List own connected devices', false],
	['delete', '/devices/:id', 'revoke_device', 'devices:write', 'Devices', 'Revoke own device', false],
].map(([method, path, id, scope, tag, summary, mcp = true]) => ({ method, path, id, scope, tag, summary, mcp, mutation: method !== 'get' && id !== 'preview_import' }));
